server:
  port: 8080
  address: 0.0.0.0  # 监听所有网络接口

spring:
  application:
    name: pattern-generator
  
  # 允许跨域请求
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"

# 日志配置
logging:
  level:
    com.lsx0500: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 自定义配置
app:
  git:
    enabled: true
    auto-push: true
  templates:
    base-path: "effects"
  output:
    base-path: "core/frontend/generated" 